package com.codigohasta.addon.modules.villager;

public enum LibrarianStep {
   NONE,
   WAIT,
   INIT_SCAN,
   WALK_TO_UNDISCOVERED,
   OPEN_FOR_DISCOVER,
   CHECK_SUPPLY,
   GOTO_EMERALD,
   TAKE_EMERALD,
   GOTO_BASE_BOOK,
   TAKE_BASE_BOOK,
   NEXT_LIBRARIAN,
   WALKING_TO_VILLAGER,
   OPEN_TRADE,
   EXECUTE_TRADE,
   CLOSE_SCREEN_AND_NEXT,
   GOTO_SORT_AREA,
   SORT_BOOKS,
   HANDLE_FULL_BOX,
   BREAK_FULL_BOX,
   GOTO_DUMP_CHEST,
   DUMP_FULL_BOX,
   GOTO_EMPTY_BOX_CHEST,
   TAKE_EMPTY_BOX,
   GOTO_PLACE_POS,
   PLACE_NEW_BOX;
}
